create table tb_users (
    user_id varchar(10) primary key,
    user_name varchar(256) not null,
    email varchar(256) not null unique,
    password varchar(256) not null,
);

create table tb_groups (
	group_id bigint generated by default as identity(start with 1) primary key,
	group_name varchar(256) not null,
	description varchar(4000)
);

create table tb_authorities (
	authority_id bigint generated by default as identity(start with 1) primary key,
	authority varchar(50) not null unique,
	description varchar(4000)
);

create table tb_group_authorities (
	group_id bigint not null,
	authority_id bigint not null,
	constraint fk_group_authorities_group
	foreign key(group_id) references tb_groups(group_id),
	constraint fk_group_authorities_authority
	foreign key(authority_id) references tb_authorities(authority_id)
);

create table tb_group_members (
	id bigint generated by default as identity(start with 1) primary key,
	group_id bigint not null,
	user_id varchar(10) not null,
	constraint fk_group_members_group
	foreign key(group_id) references tb_groups(group_id),
	constraint fk_group_members_user
	foreign key(user_id) references tb_users(user_id)
);
